<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>kazanmw.projects.perso</groupId>
  <artifactId>foldrContentOrdr</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>folderContentRenamingOrdering</name>
  <description>Project which renames content to reorder them</description>
  <dependencies>
  	<dependency>
  		<groupId>commons-io</groupId>
  		<artifactId>commons-io</artifactId>
  		<version>2.16.1</version>
  	</dependency>
  	<!-- https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
	<dependency>
	    <groupId>org.apache.commons</groupId>
	    <artifactId>commons-lang3</artifactId>
	    <version>3.17.0</version>
	</dependency>
	
  </dependencies>
  <build>
	<plugins>
		<plugin>
			<!-- Build an executable JAR -->
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-jar-plugin</artifactId>
			<version>3.1.0</version>
			<configuration>
				<archive>
					<manifest>
						<addClasspath>true</addClasspath>
						<classpathPrefix>lib/</classpathPrefix>
						<mainClass>foldersContentOrdering.FolderOrderingEngine</mainClass>
					</manifest>
				</archive>
			</configuration>
		</plugin>
	</plugins>
  </build>
</project>